name: Build & Push Container
description: Builds a container from a Dockerfile and pushes to GHCR

inputs:
  context:
    description: Effective Working Directory (e.g., ./backend or ./frontend)
    required: true
    default: "./"
  image_name:
    description: Image Name (e.g., backend or frontend)
    required: true
  github_username:
    description: Github Container Registry Username
    required: true
  github_token:
    description: Github Container Registry Authorization Token
    required: true
  ref:
    description: The checkout ref id
    required: false
    default: ""
  pr_number:
    description: Pull request number
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Checkout repository from pull request
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
      if: ${{ inputs.ref != '' }}
    - name: Checkout repository
      uses: actions/checkout@v4
      if: ${{ inputs.ref == '' }}

    - name: Set variables
      shell: bash
      run: |
        echo "SHA=sha-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "IMAGE_REVISION=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "IMAGE_VERSION=main" >> $GITHUB_ENV
        if [[ "${{ inputs.ref }}" != '' ]]; then
          git fetch origin ${{ inputs.ref }}
          echo "SHA=sha-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "IMAGE_REVISION=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "IMAGE_VERSION=pr-${{ inputs.pr_number }}" >> $GITHUB_ENV
        fi

    - name: Parse Input Values
      shell: bash
      run: |
        echo "GH_USERNAME=$(tr '[:upper:]' '[:lower:]' <<< '${{ inputs.github_username }}')" >> $GITHUB_ENV
        echo "GH_REPO=$(tr '[:upper:]' '[:lower:]' <<< '${{ github.repository }}')" >> $GITHUB_ENV

    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ env.GH_USERNAME }}
        password: ${{ inputs.github_token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Prepare Container Metadata tags
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ env.GH_REPO }}/${{ inputs.image_name }}
        # Only tag 'latest' for main branch builds (not PR builds)
        flavor: |
          latest=${{ inputs.pr_number == '' }}
        tags: |
          type=raw,value=${{ env.IMAGE_VERSION }}
          type=raw,value=${{ env.SHA }}
        labels: |
          org.opencontainers.image.revision=${{ env.IMAGE_REVISION }}
          org.opencontainers.image.version=${{ env.IMAGE_VERSION }}

    ##Temporary patch.will need to be removed after dev fix##
    - name: Patch Next.js config for Docker build
      if: ${{ inputs.image_name == 'frontend' }}
      shell: bash
      run: |
        cat > ${{ inputs.context }}/next.config.ts << 'EOF'
        import type { NextConfig } from "next";

        const nextConfig: NextConfig = {
          output: "standalone",
          typescript: { ignoreBuildErrors: true },
        };

        export default nextConfig;
        EOF
    ###Temporary patch ends here####

    - name: Build and Push to Container Registry
      id: builder
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/${{ env.GH_REPO }}/${{ inputs.image_name }}:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ env.GH_REPO }}/${{ inputs.image_name }}:buildcache,mode=max
        provenance: false
        sbom: false

    - name: Inspect Docker Image
      shell: bash
      env:
        IMAGE_NAME: ${{ inputs.image_name }}
        IMAGE_DIGEST: ${{ steps.builder.outputs.digest }}
      run: |
        docker buildx imagetools inspect "ghcr.io/${{ env.GH_REPO }}/${IMAGE_NAME}@${IMAGE_DIGEST}"
