packages:
  - frontend
  - backend

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@scarf/scarf'
  - '@swc/core'
  - core-js
  - esbuild
  - protobufjs

overrides:
  minimatch: 10.2.4
