sonar.organization=bcgov-sonarcloud
sonar.projectKey=bcgov_soba
sonar.sources=backend/src,backend/temporal-worker.ts,frontend/app,frontend/dictionaries,frontend/lib,frontend/src,.github/workflows,deployments/helm
sonar.tests=backend/tests,frontend/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/coverage/**
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.typescript.tsconfigPaths=backend/tsconfig.json,frontend/tsconfig.json
