apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "soba.fullname" . }}-backend-document-generation
  labels:
    {{- include "soba.labels" (dict "root" . "component" "backend") | nindent 4 }}
data:
  DOCUMENT_GENERATION_DEFAULT_CODE: {{ .Values.backend.config.documentGenerationDefaultCode | quote }}
  {{- with .Values.backend.documentGeneration.cdogsV2.endpoint }}
  PLUGIN_CDOGS_V2_ENDPOINT: {{ . | quote }}
  {{- end }}
  {{- with .Values.backend.documentGeneration.cdogsV2.tokenUrl }}
  PLUGIN_CDOGS_V2_TOKEN_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.backend.documentGeneration.cdogsV3.endpoint }}
  PLUGIN_CDOGS_V3_ENDPOINT: {{ . | quote }}
  {{- end }}
