apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "soba.fullname" . }}-backend
  labels:
    {{- include "soba.labels" (dict "root" . "component" "backend") | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "soba.selectorLabels" (dict "root" . "component" "backend") | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config-app: {{ include (print $.Template.BasePath "/backend/configmap-app.yaml") . | sha256sum }}
        checksum/config-formio: {{ include (print $.Template.BasePath "/backend/configmap-formio.yaml") . | sha256sum }}
        checksum/config-sso: {{ include (print $.Template.BasePath "/backend/configmap-sso.yaml") . | sha256sum }}
        checksum/config-ratelimit: {{ include (print $.Template.BasePath "/backend/configmap-ratelimit.yaml") . | sha256sum }}
        checksum/secret-db: {{ include (print $.Template.BasePath "/secrets/db-secret.yaml") . | sha256sum }}
        checksum/secret-formio: {{ include (print $.Template.BasePath "/secrets/formio-secret.yaml") . | sha256sum }}
      labels:
        {{- include "soba.selectorLabels" (dict "root" . "component" "backend") | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "soba.fullname" . }}-backend-app
            - configMapRef:
                name: {{ include "soba.fullname" . }}-backend-formio
            - configMapRef:
                name: {{ include "soba.fullname" . }}-backend-sso
            - configMapRef:
                name: {{ include "soba.fullname" . }}-backend-ratelimit
            - secretRef:
                name: {{ include "soba.fullname" . }}-db
            - secretRef:
                name: {{ include "soba.fullname" . }}-formio
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
