name: Deploy to Environment
description: Deploys CrunchyDB and app via Helm to an OpenShift namespace

inputs:
  environment:
    description: Target environment (dev, test, prod) — used for values file selection
    required: true
  job_name:
    description: Job/Instance name (master or pr-{N})
    required: true
  oc_namespace:
    description: Full OpenShift namespace (e.g., abc123-dev)
    required: true
  oc_token:
    description: OpenShift Service Account Token
    required: true
  oc_server:
    description: OpenShift API Endpoint
    required: false
    default: https://api.silver.devops.gov.bc.ca:6443
  ref:
    description: The checkout ref id
    required: false
    default: ""

runs:
  using: composite
  steps:
    # Step 1: Install oc + helm CLI
    - name: Install OpenShift CLI tools
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4.14"
        helm: "3.16"

    - name: Checkout repository from pull request
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
      if: ${{ inputs.ref != '' }}
    - name: Checkout repository
      uses: actions/checkout@v4
      if: ${{ inputs.ref == '' }}

    # Step 2: Login to OpenShift
    - name: Login to OpenShift Cluster
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ inputs.oc_server }}
        openshift_token: ${{ inputs.oc_token }}
        insecure_skip_tls_verify: true
        namespace: ${{ inputs.oc_namespace }}

    # Step 3: Deploy CrunchyDB
    - name: Deploy CrunchyDB
      uses: bcgov/action-crunchy@v1.2.6
      with:
        oc_namespace: ${{ inputs.oc_namespace }}
        oc_token: ${{ inputs.oc_token }}
        oc_server: ${{ inputs.oc_server }}
        values_file: charts/crunchy/values-${{ inputs.environment }}.yaml
        release_name: soba-db

    # Step 4: Wait for CrunchyDB
    - name: Wait for CrunchyDB
      shell: bash
      run: |
        echo "Waiting for CrunchyDB pods to be ready..."
        oc rollout status statefulset/soba-db-crunchy-db \
          --namespace ${{ inputs.oc_namespace }} \
          --watch=true --timeout=300s || true
        # Verify at least one pod is ready
        oc wait --for=condition=Ready pod \
          -l postgres-operator.crunchydata.com/cluster=soba-db-crunchy \
          --namespace ${{ inputs.oc_namespace }} \
          --timeout=300s

    # Step 5: Deploy App via Helm
    - name: Deploy App
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        RELEASE="soba-${{ inputs.job_name }}"
        NAMESPACE="${{ inputs.oc_namespace }}"
        TAG="sha-$(git rev-parse --short HEAD)"

        # Determine DB user: appproxy for main deployments, app-{PR#} for PR deployments
        if [[ "${{ inputs.job_name }}" == pr-* ]]; then
          PR_NUM=$(echo "${{ inputs.job_name }}" | sed 's/pr-//')
          DB_USER="app-${PR_NUM}"
        else
          DB_USER="appproxy"
        fi

        helm upgrade --install "${RELEASE}" charts/app/ \
          --namespace "${NAMESPACE}" \
          --set-string global.repository="${GITHUB_REPOSITORY}" \
          --set-string global.tag="${TAG}" \
          --set-string global.config.databaseUser="${DB_USER}" \
          --set-string global.databaseAlias=soba-db-crunchy \
          --wait --timeout 300s

    # Step 6: Wait for App rollout
    - name: Wait on App
      shell: bash
      run: |
        NAMESPACE="${{ inputs.oc_namespace }}"
        RELEASE="soba-${{ inputs.job_name }}"
        oc rollout status deployment/${RELEASE}-backend --namespace ${NAMESPACE} --watch=true --timeout=300s
        oc rollout status deployment/${RELEASE}-frontend --namespace ${NAMESPACE} --watch=true --timeout=300s
