apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "soba.fullname" . }}-frontend
  labels:
    {{- include "soba.labels" (dict "root" . "component" "frontend") | nindent 4 }}
data:
  NEXT_PUBLIC_SOBA_API_BASE_URL: {{ printf "https://%s/api/v1" (include "soba.backendHost" .) | quote }}
