# Test / UAT environment — two replicas, moderate resources
backend:
  replicas: 2
  sso:
    jwksUri: https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/certs
    jwtIssuer: https://test.loginproxy.gov.bc.ca/auth/realms/standard
    jwtAudience: connected-services-submit-6349
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  config:
    nodeEnv: production

frontend:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

formio:
  internal:
    enabled: true
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

mongodb:
  internal:
    enabled: true
  replicas: 1
  persistence:
    size: 2Gi
