# Dev environment — single replica, moderate resources
backend:
  # Development data generator: on in dev.
  features:
    dev-data: "enabled"
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  config:
    logLevel: debug
    nodeEnv: development
    cacheDefaultCode: cache-redis
    messagebusDefaultCode: messagebus-redis
    eventStreamDefaultCode: eventstream-redis
    documentGenerationDefaultCode: cdogs-v2
  documentGeneration:
    cdogsV2:
      endpoint: https://cdogs-dev.api.gov.bc.ca/api
      tokenUrl: https://dev.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token
    cdogsV3:
      endpoint: http://common-document-generation-service-master.a12c97-prod:3000

frontend:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi

formio:
  internal:
    enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi

mongodb:
  internal:
    enabled: true
  replicas: 1
  persistence:
    size: 1Gi

temporal:
  allowed: "true"
  address: ""
  namespace: "soba-dev"
  taskQueue: "soba"

temporalWorkers:
  - name: temporal-worker
    enabled: true
    taskQueue: "soba"
    replicas: 1
    healthPort: 9090
    resources:
      requests:
        cpu: 25m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 512Mi

  - name: temporal-worker-document-generation
    enabled: true
    taskQueue: "document-generation"
    replicas: 1
    healthPort: 9091
    resources:
      requests:
        cpu: 25m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 512Mi

vault:
  enabled: true
  role: acf456-nonprod
  secretPath: acf456-nonprod/soba-dev
  serviceAccountName: acf456-vault
